from openai import OpenAI
from core.config import settings

# Initialize the OpenAI client
client = OpenAI(api_key=settings.OPENAI_API_KEY)

def generate_code(prompt: str, language: str) -> dict:
    # Debug: Print the prompt and language
    print(f"Generating code for prompt: {prompt} in language: {language}")

    # Prepare the messages for OpenAI
    messages = [
        {"role": "system", "content": f"You are a helpful code assistant. Generate code in {language}."},
        {"role": "user", "content": prompt}
    ]

    # Debug: Print the messages being sent to OpenAI
    print(f"Sending messages to OpenAI: {messages}")

    # Call the OpenAI API
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=messages,
        max_tokens=500
    )

    # Debug: Print the OpenAI response
    print(f"OpenAI response: {response}")

    # Return the generated code and reasoning
    return {
        "code": response.choices[0].message.content,
        "reasoning": "Generated by GPT-3.5 Turbo"
    }